import os
import yaml
from pathlib import Path

def get_notebook_files(directory):
    """
    Obtiene recursivamente todos los archivos .ipynb de un directorio,
    ordenados alfabéticamente (lo que garantiza el orden por prefijo numérico).
    Excluye directorios que comiencen con '_' como _templates.
    """
    paths = []
    # Recorremos el directorio ordenado
    for entry in sorted(os.scandir(directory), key=lambda e: e.name):
        if entry.name.startswith('_'):
            continue
            
        if entry.is_dir():
            paths.extend(get_notebook_files(entry.path))
        elif entry.is_file() and entry.name.endswith('.ipynb'):
            # Guardamos la ruta relativa al directorio raíz (padre de notebooks)
            rel_path = os.path.relpath(entry.path, start=Path(directory).parent)
            # Removemos la extensión .ipynb para el toc de jupyter book
            paths.append(str(Path(rel_path).with_suffix('')).replace('\\', '/'))
            
    return paths

def generate_toc():
    """
    Genera el archivo _toc.yml leyendo la estructura de la carpeta notebooks.
    """
    base_dir = Path(__file__).parent.parent
    notebooks_dir = base_dir / 'notebooks'
    
    if not notebooks_dir.exists():
        print(f"Error: No se encontró el directorio {notebooks_dir}")
        return

    # La estructura base del TOC
    toc = {
        'format': 'jb-book',
        'root': 'README',
        'chapters': []
    }

    # Procesar cada subdirectorio de primer nivel en notebooks/
    for chapter_dir in sorted(notebooks_dir.iterdir()):
        if chapter_dir.is_dir() and not chapter_dir.name.startswith('_'):
            
            # Buscar el intro.md del capítulo
            intro_file = chapter_dir / 'intro.md'
            chapter_dict = {}
            
            if intro_file.exists():
                rel_intro = os.path.relpath(intro_file, start=base_dir)
                chapter_dict['file'] = str(Path(rel_intro).with_suffix('')).replace('\\', '/')
            else:
                print(f"Advertencia: No se encontró intro.md en {chapter_dir.name}")
                continue
            
            # Obtener los notebooks del capítulo
            notebooks = get_notebook_files(chapter_dir)
            if notebooks:
                chapter_dict['sections'] = [{'file': nb} for nb in notebooks]
                
            toc['chapters'].append(chapter_dict)

    # Escribir el _toc.yml en la raíz del proyecto
    toc_path = base_dir / '_toc.yml'
    
    # Custom dumper para evitar referencias (alias) en el YAML y mantener el orden
    class NoAliasDumper(yaml.SafeDumper):
        def ignore_aliases(self, data):
            return True

    with open(toc_path, 'w', encoding='utf-8') as f:
        f.write("# Auto-generated by scripts/generate_toc.py\n")
        yaml.dump(toc, f, Dumper=NoAliasDumper, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"Generado exitosamente: {toc_path}")

if __name__ == '__main__':
    generate_toc()